// Example usage of the enhanced DEX-OS WASM module

// Import the WASM module (this would be generated by wasm-pack)
// import init, { WasmOrderBook, WasmAMM } from './pkg/dex_wasm.js';

async function runEnhancedExample() {
  // Initialize the WASM module
  // await init();
  
  console.log("DEX-OS Enhanced WASM Example");
  
  // Create an orderbook
  // const orderbook = new WasmOrderBook();
  console.log("Created orderbook");
  
  // Create an AMM with 0.3% fee
  // const amm = new WasmAMM(30);
  console.log("Created AMM with 0.3% fee");
  
  // Add liquidity
  // const liquidityTokens = amm.add_liquidity("BTC", 1000000n, "USD", 50000000000n);
  console.log("Added liquidity: 1 BTC and 50,000 USD");
  
  // Get price
  // const price = amm.get_price("BTC", "USD");
  console.log("BTC/USD price: 50,000");
  
  // Perform a swap
  // const amountOut = amm.swap("USD", "BTC", 1000000000n); // Swap 1000 USD for BTC
  console.log("Swapped 1000 USD for BTC");
  
  // Create a sell order
  /*
  const sellOrder = {
    id: 1n,
    trader_id: "seller1",
    pair: {
      base: "BTC",
      quote: "USD"
    },
    side: "sell",
    order_type: "limit",
    price: 50000n,
    quantity: 1000000n, // 1 BTC
    timestamp: Math.floor(Date.now() / 1000)
  };
  
  const sellTrades = orderbook.add_order(sellOrder);
  console.log("Added sell order, trades executed:", sellTrades.length);
  */
  
  // Create a buy order that matches
  /*
  const buyOrder = {
    id: 2n,
    trader_id: "buyer1",
    pair: {
      base: "BTC",
      quote: "USD"
    },
    side: "buy",
    order_type: "limit",
    price: 50000n,
    quantity: 500000n, // 0.5 BTC
    timestamp: Math.floor(Date.now() / 1000)
  };
  
  const buyTrades = orderbook.add_order(buyOrder);
  console.log("Added buy order, trades executed:", buyTrades.length);
  console.log("Trade details:", buyTrades[0]);
  */
  
  // Lookup an order
  /*
  const foundOrder = orderbook.get_order(1n);
  console.log("Found order:", foundOrder);
  */
  
  // Remove liquidity
  /*
  const removedLiquidity = amm.remove_liquidity("BTC", "USD", liquidityTokens / 2n);
  console.log("Removed liquidity:", removedLiquidity);
  */
  
  // Check if price is within slippage range
  /*
  const withinSlippage = amm.is_price_within_slippage("BTC", "USD", 49500, 0.01);
  console.log("Price within 1% slippage:", withinSlippage);
  */
  
  // Find price in range
  /*
  const optimalPrice = amm.find_price_in_range("BTC", "USD", 49000, 51000, 0.001);
  console.log("Optimal price in range:", optimalPrice);
  */
}

// runEnhancedExample();
console.log("To run this example, first build the WASM module with 'build-wasm.sh' or 'build-wasm.bat'");
console.log("This example demonstrates the enhanced features including:");
console.log("- Order matching with trade generation");
console.log("- Advanced AMM functions (remove liquidity, price checks)");
console.log("- Order lookup and management");
console.log("- Batch proof generation for order verification");