// Example usage of the DEX-OS WASM module

// Import the WASM module (this would be generated by wasm-pack)
// import init, { WasmOrderBook, WasmAMM } from './pkg/dex_wasm.js';

async function runExample() {
  // Initialize the WASM module
  // await init();
  
  console.log("DEX-OS WASM Example");
  
  // Create an orderbook
  // const orderbook = new WasmOrderBook();
  console.log("Created orderbook");
  
  // Create an AMM with 0.3% fee
  // const amm = new WasmAMM(30);
  console.log("Created AMM with 0.3% fee");
  
  // Add liquidity
  // const liquidityTokens = amm.add_liquidity("BTC", 1000000n, "USD", 50000000000n);
  console.log("Added liquidity: 1 BTC and 50,000 USD");
  
  // Get price
  // const price = amm.get_price("BTC", "USD");
  console.log("BTC/USD price: 50,000");
  
  // Perform a swap
  // const amountOut = amm.swap("USD", "BTC", 1000000000n); // Swap 1000 USD for BTC
  console.log("Swapped 1000 USD for BTC");
}

// runExample();
console.log("To run this example, first build the WASM module with 'build-wasm.sh' or 'build-wasm.bat'");